version: '3'

services:
  apisix:
    image: apache/apisix:3.9.0-debian
    container_name: apisix-standalone
    ports:
      - "9080:9080"
    volumes:
      - ./config/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./config/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    environment:
      - APISIX_STAND_ALONE=true
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
    networks:
      - apisix-network

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr"
      - ":8181"
      - "--log-level=debug"
      - "--watch"
      - "/policies/policy.rego"
    volumes:
      - ./opa_policies:/policies:ro
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - TENANT_ID=${TENANT_ID}
    networks:
      - apisix-network

  backend:
    image: kennethreitz/httpbin
    container_name: backend-service
    networks:
      - apisix-network

networks:
  apisix-network:
    driver: bridge
